sudo: required
services:
  - docker

before_install:
  - docker build -t rohitaror/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rohitaror/react-test npm test

after_success:
  - docker build -t rohitaror/multi-client ./client
  - docker build -t rohitaror/multi-nginx ./nginx
  - docker build -t rohitaror/multi-server ./server
  - docker build -t rohitaror/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD"  | docker login -u "DOCKER_ID" --password-stdin

  - docker push rohiaror/rohitaror:multi-client 
  - docker push rohiaror/rohitaror:multi-nginx
  - docker push rohiaror/rohitaror:multi-server
  - docker push rohiaror/rohitaror:multi-worker 