sudo: required
services:
  - docker

before_install:
  - docker build -t rohitaror/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rohitaror/react-test npm test

after_success:
  - docker build -t rohiaror/multi-client ./client
  - docker build -t rohiaror/multi-nginx ./nginx
  - docker build -t rohiaror/multi-server ./server
  - docker build -t rohiaror/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD"  | docker login -u "$DOCKER_ID" --password-stdin

  - docker push rohiaror/multi-client
  # - docker push rohitaror/multi-nginx
  # - docker push rohitaror/multi-server
  # - docker push rohitaror/multi-worker  